// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX8gPGkFFCSi69H-se8zcjS-gncCdd5LY',
    appId: '1:184859242203:android:a06109ec8e8ecfa59526fe',
    messagingSenderId: '184859242203',
    projectId: 'nexa-app-prod',
    storageBucket: 'nexa-app-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGK4p42wMKFKbkAKghwgDCDHjPZZ42zy8',
    appId: '1:184859242203:ios:b3fc4b7fd3677f259526fe',
    messagingSenderId: '184859242203',
    projectId: 'nexa-app-prod',
    storageBucket: 'nexa-app-prod.firebasestorage.app',
    androidClientId: '184859242203-ra3uf6sjj2ri6j2buv0f1niem0tabr38.apps.googleusercontent.com',
    iosClientId: '184859242203-v7lmaq2j7pdsu1tpd7tj7ov8s63n1g0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.nexaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3fvZ-FDftcy9JhZv3kHb2_dVCT6KS7jM',
    appId: '1:184859242203:web:89be694c8812b4c59526fe',
    messagingSenderId: '184859242203',
    projectId: 'nexa-app-prod',
    authDomain: 'nexa-app-prod.firebaseapp.com',
    storageBucket: 'nexa-app-prod.firebasestorage.app',
  );

}